### ISSUE TITLE
setup.py has no license information

### ISSUE THREAD

**Issue by kwijk** [jax-ml/ml_dtypes#115]
# Actual behavior

I work on commercial application and install ml_dtypes as dependency of tensorflow
In order to prevent some gpl licensed software in our commercial product we parse pip packages to obtain the license info and raise warnings if the license is not on a white list. (using pkg_resources or importlib)

You setup.py does not contain any license information, so it fails to pass our test. Instead the license is in separate LICENSE file but it is not referenced in setup.py.

# Expected behaviour

setup.py contains the following

``` python
setup(
    ...
    license="Apache-2.0",
    ...
)
```

**Comment by jakevdp** [comment]
In this package, `setup.py` mainly exists for reasons related to building of the extension modules. The main package metadata is declared in `pyproject.toml`: https://github.com/jax-ml/ml_dtypes/blob/348fd3704306cae97f617c38045cee6bc416bf10/pyproject.toml#L7-L15

**Comment by kwijk** [comment]
Ah, off course. Yes, we should update our processes. This ticket can be closed.
