### ISSUE TITLE
Adept to NumPy change

### ISSUE THREAD

**Issue by seberg** [jax-ml/ml_dtypes#135]
To allow changing the details of NumPy DTypes/descriptor struct, I need to slightly backwards compatible changes to the registration.

Since `ml_types` is probably the larger open source place, just a heads up:  You will need to do some slight modifications: https://numpy.org/devdocs/reference/c-api/array.html#c.PyArray_RegisterDataType (missing colon in the doc rendering, but I think you can get the idea).

**Comment by jakevdp** [comment]
Thanks! Fixed by #136
