### ISSUE TITLE
Update to Numpy 2.0?

### ISSUE THREAD

**Issue by sbrl** [jax-ml/ml_dtypes#159]
Hello,

This package is a blocker for a number of high-profile packages to update to Numpy 2.0, including `tensorflow` and `transformers`.

Given that Numpy was release on 19th June 2024 and this apckage last released on 24th April, and given I experience the following crash when attempting to use either of the above 2 packages with Numpy 2.0:

https://pastebin.com/raw/rFH6yg1P

....it stands to reason that this package is the root cause.

**Comment by jakevdp** [comment]
Hi - the ml_dtypes 0.4.0 release (dated April 1 2024) supports NumPy 2.0.

The error message you pasted seems to come from tensorflow, which to my knowledge does not yet have a NumPy 2.0 compatible release (see https://github.com/tensorflow/tensorflow/issues/67291)

**Comment by hawkinsp** [comment]
Nothing to do here: this issue is filed against the wrong package.
