### ISSUE TITLE
Support unpacked FP4E2M1

### ISSUE THREAD

**Issue by justinchuby** [jax-ml/ml_dtypes#164]
Creating this tread from https://github.com/jax-ml/ml_dtypes/issues/116 for a focused proposal on supporting FP4E2M1. Thanks!

**Comment by balancap** [comment]
From my experience implementing #166 , I believe the present `float8_base` can be adapted without much difficulty to support FP4 (and FP6) dtypes.

I would follow the suggestion of @cloudhan, adding a type traits `sizeof_bits` specialized for FP4/FP6 formats to give the proper bit size of every dtype. Then using `sizeof_bits`, `TraitsBase` can be extended to have proper bitmasking for the exponent and mantissa parts (https://github.com/jax-ml/ml_dtypes/blob/main/ml_dtypes/include/float8.h#L891). The rest should almost work out of the box :)

**Comment by justinchuby** [comment]
@hawkinsp thanks! Do you know when it will be released?

**Comment by hawkinsp** [comment]
Today, hopefully.

**Comment by justinchuby** [comment]
That’s amazing, thank you!
