### ISSUE TITLE
Updating v0.2.0: Adding new float8 type (fp8e4_m3)

### ISSUE THREAD

**Issue by tapan0007** [jax-ml/ml_dtypes#165]
Hi,

I am currently using version 0.2.0 of the JAX ml-dtypes library, as our project supports only Python 3.8. I need to update this version to include the new float8 type (fp8e4_m3), create a new release (version 0.2.1), and make my library dependent on this updated version. Could you please guide me on how to achieve this?

Thank you,
Tapan

**Comment by jakevdp** [comment]
Hi - unfortunately we're not well set up to do these kinds of patch releases. Python 3.8 is near its end of life (October 2024) and projects following [SPEC-0](https://scientific-python.org/specs/spec-0000/) have dropped Python 3.8 support nearly two years ago, in October 2022. Given that, I don't think it's warranted to do a Python 3.8 back-port of newer features, and your effort would be better spent updating your systems to Python 3.9 or newer.

**Comment by hawkinsp** [comment]
Closing, because I think Jake answered this.
