### ISSUE TITLE
[Question] Can we release a new version of ml_dtypes?

### ISSUE THREAD

**Issue by apivovarov** [jax-ml/ml_dtypes#185]
I discovered that JAX CI relies on the PyPI repository to install ml_dtypes.

As a result, JAX CI is unable to build my PR (https://github.com/google/jax/pull/23585 Add float8_e4m3 type support) because the version of ml_dtypes on PyPI (0.4.0, released on April 1, 2024) is outdated.

**Comment by jakevdp** [comment]
Yes, we're planning another release very soon. There are a few PRs in review that we'd like to get in, and then we'll likely do a release.

**Comment by hawkinsp** [comment]
Done (0.5.0).

**Comment by apivovarov** [comment]
Thank you!
