### ISSUE TITLE
float8_e4m3fn round 4.25 to 4

### ISSUE THREAD

**Issue by jq** [jax-ml/ml_dtypes#221]
ML types version 0.4.0 and on mac. 

`print(f"bug {float8_e4m3fn(4.25)}") ` give 4 instead of 4.5, that seems a bug,  since float8_e4m3fn has 4.5
https://asawicki.info/articles/fp8_tables.php

**Comment by jq** [comment]
got it, so the round is follow always round to <0.5,  Thanks
seems we need stochastically round

**Comment by jakevdp** [comment]
I can't find the reference for it, but I think this uses round-to-nearest-even semantics.
