### ISSUE TITLE
Package vendoring issues

### ISSUE THREAD

**Issue by daskol** [jax-ml/ml_dtypes#51]
I clearly understand that the project is on early stage and everything could change in the future.

1. However, I'd like to propose relax version requirements in build dependencies since rolling release distros like Arch usually has newer releases what results in annoying [patching][1].

2. Another one request is to clone `Eigen` submodule to `eigen3` not just `eigen`. The issue is that its installation paths starts with `eigen3` not `eigen`. This allows to reuse Eigen installed system wide.

[1]: https://aur.archlinux.org/cgit/aur.git/tree/ml-dtypes.diff?h=python-ml-dtypes

**Comment by daskol** [comment]
Well, I'm not sure about your intentions but I'd like to see dependency on `numpy` or `oldest-supported-numpy` in `>=` fashion rather than `~=` with explicit restrictions from above if needed (e.g. `numba` requires `numpy<1.25` recently).

**Comment by daskol** [comment]
I mean [build dependencies](https://github.com/jax-ml/ml_dtypes/blob/v0.0.4/pyproject.toml#L46-L54).

> Is it that you'd like us to specify a maximum supported numpy version in addition to a minimum supported?

Yes. Is there any obstacles?

**Comment by jakevdp** [comment]
Oh those build dependencies *need* to be set to the oldest supported numpy version, because numpy ABI is backward compatible but not generally forward compatible. If we didn't pin the oldest version there, then the pre-built wheels released on PyPI would not be compatible with the full range of versions specified in the install requirements.

Does that make sense?

**Comment by daskol** [comment]
Yes, sure. It makes sense to simplify wheel building on developer side but you could necessary pin this version and install explicitly needed `numpy` in that GitHub Action. What do you think about distributing manylinux wheels? As far as I know, C++17 requires quite a recent distro for binary compatibility.

For the record, wheels are great for distribution in general case but sometimes you use MKL or any custom other BLAS/LAPACK. The issue is that you should usually rebuild all descendant in order to avoid binary compatibility issues or issues in linking type as an example. In such a case, package building usually is not isolated in sense of PEP-517. And pinned build dependency is a headache.

**Comment by jakevdp** [comment]
Thanks for the clarification.

So, just to be clear, in the package vendoring context you're thinking of, it's not a problem that building with the wrong numpy version renders the `install_requires` field incorrect?

**Comment by daskol** [comment]
> in the package vendoring context you're thinking of, it's not a problem that building with the wrong numpy ABI version renders the install_requires field incorrect?

Yes, I thinks that it is not a problem. But I am agreed that it is convenient for you to pin numpy version in `pyproject.toml`.

> We do distribute manylinux wheels, both for x86_64 and aarch64.

Sorry, I did read the workflow inattentive.

**Comment by jakevdp** [comment]
OK - do you know of other projects that depend on the numpy ABI, use `pyproject.toml`, and have behavior more inline with what you're requesting here? I'd be curious to see how they specify their build-time and install-time dependencies.

**Comment by daskol** [comment]
This is a good question! I have never seen anything other than enumerating dependencies without versions. If you come across something, please let me know. Currently my working solution is to by-pass build dependency check (e.g. `python -m build -n -w -x`) but the situation is generally confusing for end users, I think.

Thank you for your time.

**Comment by jakevdp** [comment]
I thought I'd cross-link here because I thought it was interesting: SciPy has a similar build setup and got a similar request, and the discussion is illuminating: https://github.com/scipy/scipy/issues/18767

In particular, they suggest some mechanisms that can be used in case a particular user wants to customize their build environment.
