### ISSUE TITLE
Limited bfloat16 precision breaks reduction operations

### ISSUE THREAD

**Issue by mrahtz** [jax-ml/ml_dtypes#63]
We've been seeing some funny results when trying to do analysis on model activations stored as bfloat16 NumPy arrays. The crux of the issue seems to be that reduction on bfloat16 arrays uses bfloat16 precision for the accumulator (at least I _guess_ that's what's happening), which can lead to some funny results. For example:

```python
np.random.uniform(size=(10000,)).astype(np.dtype('bfloat16')).sum() == 256
# but also
np.random.uniform(size=(20000,)).astype(np.dtype('bfloat16')).sum() == 256
```

The precision of bfloat16 at 256 is only about 1 or 2 - so once the accumulator reaches a value of 256, all the subsequent additions of like `0.1` get rounded down to 256, so the accumulator can never grow larger.

Some specific situations where we've seen errors because of this include centering (where we need to compute a mean), and we think also matrix multiplication (since I guess that also involves accumulation).

Thanks!

**Comment by jakevdp** [comment]
For what its worth, some libraries that support bfloat16 do automatically choose to accumulate in higher precision; for example, here's the result in JAX:
```python
import jax.numpy as jnp
import numpy as np

vals = np.random.uniform(size=(10000,)).astype(np.dtype('bfloat16'))
print(vals.sum())
# 256

print(jnp.array(vals).sum())
# 4960
```

**Comment by mrahtz** [comment]
Thanks for the super quick reply!

>For what its worth, some libraries that support bfloat16 do automatically choose to accumulate in higher precision; for example, here's the result in JAX

Right, sorry for forgetting to mention - that's the key thing that stumped us here/that seems potentially 'wrong' - that we work a lot with both JAX and NumPy, and expect them to behave as similarly as possible. It's super unexpected when operations turn out dramatically different depending on whether we do them in JAX, or `device_get()` them and do them in NumPy. In some cases, it's been more than just small, insignificant numerical differences - it's been the difference between analyses turning out completely differently depending on whether we accidentally converted to NumPy or not.

On the other hand, it's true there is already precedent for differences in dtype behaviour between NumPy and JAX. I'm thinking of matrix multiplication precision in particular - the fact that JAX accumulates matrix multiplications in bfloat16 by default even if the operands are float32, which of course NumPy doesn't do. At least with that particular case, once the user has discovered it, it's configurable - so maybe one way forward would be to make accumulation precision on bfloat16s configurable in NumPy too?

Even if that turns out not to be possible, I'm wondering whether it would be at least worth documenting this in e.g. `ml_dtypes`'s README so there's a standard explanation to point folks to.

**Comment by jakevdp** [comment]
Got it, thanks. Since this repo doesn't implement any computations like `sum`, would it be sufficient to add something in the README along the lines of  this?

> Note that libraries that use these dtypes (like `numpy`, `jax`, `tensorflow`, etc.) may have different implementations for opertions on arrays with these dtypes.

**Comment by jakevdp** [comment]
> maybe one way forward would be to make accumulation precision on bfloat16s configurable in NumPy too?

That would be a question for the NumPy team. This repo has no control over what numpy does with the dtypes it defines.

**Comment by mrahtz** [comment]
> > Got it, thanks. Since this repo doesn't implement any computations like sum, would it be sufficient to add something in the README along the lines of this?
> 
> Note that libraries that consume these dtypes (like numpy, jax, tensorflow, etc.) may have different implementations for operations on arrays with these dtypes.

Yup, basically sounds good. I think it would be worth calling out the accumulation thing in particular to give people a flavour of the particular kind of thing that can do wrong. It might even be worth mentioning the `np.random.uniform(size=(10000,)).astype(np.dtype('bfloat16')).sum() == 256` example specifically - I think it has a pretty strong shock value, and shock is a good teacher :)

> > maybe one way forward would be to make accumulation precision on bfloat16s configurable in NumPy too?
> 
> That would be a question for the NumPy team. This package has no control over what numpy does with the dtypes defined here.

Fair; I'll raise an issue with NumPy, then.

**Comment by jakevdp** [comment]
I added some discussion of this in the README in #64, let me know if you have any thoughts!

**Comment by mrahtz** [comment]
That's fantastic - thank you very much for such a quick response!
